server:
  port: 8003
spring:
  application:
    name: Cloud-Provide
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/provide8003
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: Mysql1234.
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
  mybatis: mapper-locations=classpath*:/mapper/*Mapper.xml
eureka:
  instance:
    instance-id: Cloud-Provide-8003
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
info:
  app:
    name: 消费者-8003
  company:
    name: www.cloud.com
  build:
    artifactId: ${project.artifactId}
    version: ${project.version}